# Generated by Django 5.2.7 on 2025-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=12)),
                ('cidade', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
